### ISSUE TITLE
Major goals

### ISSUE THREAD

**Issue by abraham** [abraham/twitteroauth#686]
This s a summary of the plans for TwitterOAuth future major versions.

Once released, 1.0 will only receive critical bug fixes. It will have its own branch and master branch will be working towards the goals listed below. If you are interested in implementing any of these, go comment on the particular issue.

**Planned**
- [x] Drop support for PHP < 7.1 (#678)
- [x] Enable strict_types and type declarations (#679)
- [x] Switch to recorded HTTP requests in tests (#671) 
- [ ] Explore switching to guzzle (#680)
- [ ] `File` class for handling media files (#681)
- [ ] `Response` class for handling responses (#683)
- [ ] Throw exceptions for non-2XX responses (#682)
- [ ] Support additional API hosts (#684)
- [ ] Add better per request configuration (#685)

**Under consideration**
- [ ] Streaming support (#295)
- [ ] Everything else in the issue tracker

**Comment by hlashish** [comment]
Hi Sir 
I am still waiting for your response, please help me out. I am stocked from almost a month , trying to figure out the cause.

**Comment by abraham** [comment]
@hlashish please create a new issue that describes exactly what you are trying to do, what you expect to happen and what is actually happening.

**Comment by hlashish** [comment]
Hi Abraham


Thanks for quick response. I am creating the new issue in git hub now and
will mention the details of my work in it.

Once again thanks a lot, your response generated a new hope in me.


Regards
Ashish Joshi

**Comment by Eksilente** [comment]
Any updates on this please?

I am facing the same issue. I can post status update but when trying to send direct message I got this 
![screenshot from 2018-10-13 02-35-05](https://user-images.githubusercontent.com/3522171/46887766-1e602f80-ce91-11e8-9779-bd766ebcd1c2.png)

I got http code 400 which means Bad Request = Invalid ..... according to the documentation
and message not sent.

I use the same token and secret in posting status update and it successfully tweeted. Any idea please? Could it be from twitter itself? we already have the direct_message permission and have been revoking and re-authenticating the app multiple times, still wont work. Please help.

**Comment by lrf141** [comment]
@abraham I am often indebted to this software. So, I want to contribute to this issues. 
Can I work on this problem? -> "Enable strict_types and type declarations"

**Comment by abraham** [comment]
TwitterOAuth is in maintenance mode and major improvements are no longer planned. https://github.com/abraham/twitteroauth/issues/1188
